import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy — DrawLint.ai",
  description: "How DrawLint.ai collects, uses, and protects your data.",
};

export default function PrivacyPolicyPage() {
  const lastUpdated = "April 26, 2026";

  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="mx-auto max-w-3xl px-4 py-16">
        {/* Header */}
        <div className="mb-12">
          <Link href="/" className="text-sm text-muted-foreground hover:text-foreground transition-colors">
            ← Back to Home
          </Link>
          <h1 className="mt-4 text-3xl font-bold tracking-tight">Privacy Policy</h1>
          <p className="mt-2 text-sm text-muted-foreground">Last updated: {lastUpdated}</p>
        </div>

        <div className="space-y-8 text-sm leading-relaxed text-muted-foreground [&_h2]:text-lg [&_h2]:font-semibold [&_h2]:text-foreground [&_h2]:mb-3 [&_h3]:text-base [&_h3]:font-medium [&_h3]:text-foreground [&_h3]:mb-2 [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:space-y-1">

          <section>
            <h2>1. Overview</h2>
            <p>
              DrawLint.ai (&quot;we&quot;, &quot;us&quot;, &quot;our&quot;) is an AI-powered system design review platform.
              This Privacy Policy explains how we collect, use, store, and protect your personal information
              when you use our website and services at{" "}
              <a href="https://drawlint.ai" className="text-violet-400 hover:underline">drawlint.ai</a>.
            </p>
          </section>

          <section>
            <h2>2. Information We Collect</h2>

            <h3>Account Information</h3>
            <ul>
              <li><strong>Email address</strong> — used for authentication, email verification, and transactional emails.</li>
              <li><strong>Display name</strong> — shown on your public submissions.</li>
              <li><strong>OAuth profile data</strong> — when you sign in with Google or GitHub, we receive your name, email, and profile picture from the provider. We do not access your repositories, contacts, or other data.</li>
            </ul>

            <h3>Design Data</h3>
            <ul>
              <li><strong>System design diagrams</strong> — the drawings you create and submit for review.</li>
              <li><strong>AI review results</strong> — the feedback generated by our AI reviewers.</li>
              <li><strong>Your responses</strong> — text you write when responding to AI feedback.</li>
            </ul>

            <h3>API Keys (BYO Mode)</h3>
            <ul>
              <li>If you choose to bring your own AI provider (Gemini or Azure OpenAI), your API keys are stored <strong>locally in your browser&apos;s localStorage</strong>.</li>
              <li>Keys are sent to our server only during analysis requests and are <strong>never stored on our servers</strong>.</li>
              <li>Clearing your browser data will remove your stored keys.</li>
            </ul>

            <h3>Automatically Collected Data</h3>
            <ul>
              <li><strong>Cookies</strong> — we use essential cookies for authentication (session management via NextAuth.js). We do not use tracking or advertising cookies.</li>
              <li><strong>Server logs</strong> — standard web server logs (IP address, browser type, access times) for security and debugging purposes.</li>
            </ul>
          </section>

          <section>
            <h2>3. How We Use Your Information</h2>
            <ul>
              <li>To provide and maintain the DrawLint.ai service.</li>
              <li>To authenticate your identity and manage your account.</li>
              <li>To process your design diagrams through AI review.</li>
              <li>To send transactional emails (verification, welcome).</li>
              <li>To improve our service and fix issues.</li>
            </ul>
            <p className="mt-2">We do <strong>not</strong> sell, rent, or share your personal information with third parties for marketing purposes.</p>
          </section>

          <section>
            <h2>4. Third-Party Services</h2>
            <p>We use the following third-party services to operate DrawLint.ai:</p>
            <ul>
              <li><strong>Microsoft Azure</strong> — hosting, database (Cosmos DB), and AI services (Azure OpenAI) for managed AI reviews.</li>
              <li><strong>Google OAuth</strong> — optional sign-in provider. Subject to <a href="https://policies.google.com/privacy" className="text-violet-400 hover:underline" target="_blank" rel="noopener noreferrer">Google&apos;s Privacy Policy</a>.</li>
              <li><strong>GitHub OAuth</strong> — optional sign-in provider. Subject to <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement" className="text-violet-400 hover:underline" target="_blank" rel="noopener noreferrer">GitHub&apos;s Privacy Statement</a>.</li>
              <li><strong>Google Gemini API</strong> — if you choose the free AI option, your design data is sent to Google&apos;s Gemini API for analysis. Subject to <a href="https://ai.google.dev/gemini-api/terms" className="text-violet-400 hover:underline" target="_blank" rel="noopener noreferrer">Gemini API Terms</a>.</li>
              <li><strong>Resend</strong> — transactional email delivery.</li>
            </ul>
          </section>

          <section>
            <h2>5. Data Storage & Security</h2>
            <ul>
              <li>Your data is stored on Microsoft Azure infrastructure.</li>
              <li>Passwords are hashed using bcrypt before storage.</li>
              <li>Authentication tokens are signed with HMAC-SHA256 and stored in HttpOnly Secure cookies.</li>
              <li>All data is transmitted over HTTPS.</li>
              <li>BYO API keys are stored only in your browser and never persisted on our servers.</li>
            </ul>
          </section>

          <section>
            <h2>6. Data Retention</h2>
            <ul>
              <li>Account data is retained as long as your account is active.</li>
              <li>Design submissions and reviews are retained indefinitely unless you delete them.</li>
              <li>You may request deletion of your account and all associated data by contacting us.</li>
            </ul>
          </section>

          <section>
            <h2>7. Your Rights</h2>
            <p>You have the right to:</p>
            <ul>
              <li><strong>Access</strong> your personal data stored by us.</li>
              <li><strong>Correct</strong> inaccurate data.</li>
              <li><strong>Delete</strong> your account and all associated data.</li>
              <li><strong>Export</strong> your design data.</li>
              <li><strong>Withdraw consent</strong> for data processing at any time.</li>
            </ul>
            <p className="mt-2">
              To exercise any of these rights, contact us at{" "}
              <a href="mailto:drawlint.ai.support@gmail.com" className="text-violet-400 hover:underline">drawlint.ai.support@gmail.com</a>.
            </p>
          </section>

          <section>
            <h2>8. Children&apos;s Privacy</h2>
            <p>
              DrawLint.ai is not directed at children under 13. We do not knowingly collect personal information
              from children under 13. If you believe a child has provided us with personal data, please contact us.
            </p>
          </section>

          <section>
            <h2>9. Changes to This Policy</h2>
            <p>
              We may update this Privacy Policy from time to time. We will notify you of material changes by
              posting the new policy on this page and updating the &quot;Last updated&quot; date.
            </p>
          </section>

          <section>
            <h2>10. Contact</h2>
            <p>
              If you have questions about this Privacy Policy, contact us at:{" "}
              <a href="mailto:drawlint.ai.support@gmail.com" className="text-violet-400 hover:underline">drawlint.ai.support@gmail.com</a>
            </p>
          </section>
        </div>

        {/* Footer */}
        <div className="mt-16 border-t border-border pt-8 text-center text-xs text-muted-foreground">
          <div className="flex items-center justify-center gap-3">
            <Link href="/" className="hover:text-foreground transition-colors">Home</Link>
            <span className="text-muted-foreground/30">·</span>
            <Link href="/terms" className="hover:text-foreground transition-colors">Terms of Service</Link>
            <span className="text-muted-foreground/30">·</span>
            <Link href="/support" className="hover:text-foreground transition-colors">Support</Link>
          </div>
        </div>
      </div>
    </div>
  );
}
